export const Table=[
    {
        tableNo:231,
        seatingCapacity:5,
        status:'Available',
        reservation:{},
        orders:[]
    },
    {
        tableNo:232,
        seatingCapacity:5,
        status:'Available',
        reservation:{},
        orders:[]
    },
    {
        tableNo:234,
        seatingCapacity:5,
        status:'Available',
        reservation:{},
        orders:[]
    },
    {
        tableNo:235,
        seatingCapacity:1,
        status:'Available',
        reservation:{},
        orders:[]
    },
    {
        tableNo:320,
        seatingCapacity:2,
        status:'Available',
        reservation:{},
        orders:[]
    },
    {
        tableNo:321,
        seatingCapacity:3,
        status:'Reserved',
        reservation:{
            name:'Ak'
        },
        orders:[]
    },
    {
        tableNo:322,
        seatingCapacity:4,
        status:'Available',
        reservation:{},
        orders:[]
    }
]